

CREATE TABLE [dbo].[UserMovieBase](
	[Id] [int] NOT NULL IDENTITY(1,1),
	[UserId] [int] NULL,
	[MovieId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[UserMovieBase]  WITH CHECK ADD FOREIGN KEY([MovieId])
REFERENCES [dbo].[MovieBase] ([Id])
GO

ALTER TABLE [dbo].[UserMovieBase]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[UserBase] ([Id])
GO


